development:
  adapter: postgresql
  encoding: unicode
  database: burndown_development
  pool: 5
  host: postgres
  username: postgres
  password: secret

test:
  adapter: postgresql
  encoding: unicode
  database: burndown_test
  pool: 5
  host: postgres
  username: postgres
  password: secret